---
title: "Incorporate Amenity weight with score"
author: "Yuxuan"
date: "26/05/2021"
output: html_document
---

#### Load libraries
```{r message=FALSE, warning=FALSE}
library(dplyr)
library(readr)
library(reshape)

```

#### Import data



```{R message=FALSE, warning=FALSE}
poi_index <- read_csv("data/amenity_score/poi_index.csv")
van_poi<-read_csv("~/Desktop/MDS/data599/w2020-data599-capstone-projects-statistics-canada-transit/data/clean/vancouver_facilities_2.csv")
ttm <- read_csv("~/Desktop/MDS/data599/data/procceddata/ttm.csv")
vancouver_db <- read_csv("data/clean/vancouver_db.csv")
```


#### inner join the ttm with poi index (4 types of poi)
```{R}
poi_index%>%select(id,Index,type)->index
ttm_poi<-inner_join(ttm,index,by=c("toId"="id"))
ttm_poi
```


```{R}
# avg travel time to all accessible destinations
ttm_all_dest <- ttm_poi %>%
                group_by(fromId,type) %>% 
                summarise(
                  avg_time_to_allpoi = mean(avg_unique_time), 
                  avg_sd_time_to_uniquepoi = mean(sd_unique_time),
                  n_accessible_poi_weighted = sum(Index),
                  n_accessible_poi_unweighted=n())
                

ttm_all_dest
```

#### compute score

```{R}
ttm_all_dest[ttm_all_dest==0] <- .00001
ttm_all_dest%>%mutate(score_weighted=n_accessible_poi_weighted/(avg_time_to_allpoi*avg_sd_time_to_uniquepoi),score_unweighted=n_accessible_poi_unweighted/(avg_time_to_allpoi*avg_sd_time_to_uniquepoi))->score_set
# weighted score
score_set%>%select(fromId,type,score_weighted,score_unweighted)->score_set
```

```{R}
# melt the score set 
library(tidyr)
long_score <- score_set %>% gather(Scoring_Scheme, value, -c(fromId, type))
long_score
```

```{R}
score_long<-left_join(long_score,vancouver_db,by=c("fromId"="id"))
```


#### export csv 

```{R}

write.csv(score_long,'/Users/yuxuancui/Desktop/MDS/data599/Amenity_index/long_score.csv',row.names = FALSE)
```


```{R}
unique(score_long$type[which(score_long$Scoring_Scheme=="score_unweighted")])
score_long

```


```{r}
par(mfrow = c(2, 3))
plot(density(ttm_all_dest$avg_time_to_allpoi))
plot(density(ttm_all_dest$avg_sd_time_to_uniquepoi))
plot(density(ttm_all_dest$n_accessible_poi))
```
