---
title: "New_scores"
author: "Rain Shen"
date: "5/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load libraries
```{r message=FALSE, warning=FALSE}
library(dplyr)
library(readr)
library(reshape)
library(ggplot2)
```

### Import and organize data sets

```{R message=FALSE, warning=FALSE}

poi_wt <- read_csv("poi_index.csv")
van_poi <- read_csv("vancouver_facilities_2.csv")
ttm <- read_csv("ttm.csv")
# vancouver_db <- read_csv("vancouver_db.csv")

colnames(ttm)[2] <- "id"
poi_wt <- poi_wt[, c(6,7)] # keep weight, id
names(poi_wt) <- c('weight', 'id')

van_poi <- van_poi[, c(1,4)] # keep id, type

# Select 4 POIs that are interested in
target_amenities <- c('gallery', 'museum', 'library or archives', 'theatre/performance and concert hall')
poi_4 <- van_poi %>% filter(type %in% target_amenities)

```


### Join ttm and amenities with types and weights

```{R}
# Merge all 3 data sets
ttm_type <- Reduce(function(x,y) merge(x, y, by="id", all=TRUE), list(ttm, poi_4, poi_wt))
ttm_type <- ttm_type[, c(2,1,3,4,5,6)]
colnames(ttm_type)[2] <- "toId"

# If any weights are undefined replace with 0
ttm_type$weight[is.na(ttm_type$weight)] <- 0

# Remove destinations that cannot be reached
ttm_type <- ttm_type[complete.cases(ttm_type), ]
head(ttm_type)
apply(ttm_type, 2, function(x) sum(is.na(x)))

```


```{r}
# Normalize vector to a custom range [x,y]

normalize_vec <- function(vec, x=0.01, y=0.99, log = FALSE) {
  if (log == TRUE) { vec <- log(vec) }
  norm_v <- (vec - min(vec))/(max(vec) - min(vec))
  custom_norm_v <- norm_v*(y - x) + x
  custom_norm_v
}


# Normalize all numeric columns in a dataframe to a custom range [x,y]

normalize_df <- function(df, x = 0.01, y = 0.99, log = FALSE) {
  num_cols <- which(sapply(df, is.numeric)) # numeric columns
  normed <- sapply(df[num_cols], normalize_vec, x = x, y = y, log = log)
  df[num_cols] <- (normed)
  df
}
```


## New method for computing scores 

```{R}
# Using 1/(mean + 2*sd) for each fromId & toId combination
score_all <- ttm_type %>% 
  mutate(weighted_score = (1+weight)/(avg_unique_time + 2*sd_unique_time), 
         raw_score = 1/(avg_unique_time + 2*sd_unique_time))

score_all$fromId <- as.factor(score_all$fromId)

# To obtain score for each fromId & type combination
score_type <- score_all %>% 
  group_by(fromId, type) %>% 
  summarise(
    weighted_score_all = sum(weighted_score),
    raw_score_all = sum(raw_score))
range(score_type$weighted_score_all)
range(score_type$raw_score_all)

# Normalize scores
# normalize <- function(x){(x-min(x))/(max(x)-min(x))}
# scores <- score_type %>%
#      mutate_at(vars(matches("score")), normalize)
score_type <- normalize_df(score_type, x = 0.001, y = 0.999, log = FALSE)
range(score_type$weighted_score_all)
range(score_type$raw_score_all)

```

```{r}
# function to plot score distributions by type
plot_densities <- function(score_frame1, score_frame2, titl1, titl2) {
  x <- score_frame1 %>%
        ggplot(aes(x = score, color = type)) +
        geom_density() +
        egg::theme_article() +
        theme(aspect.ratio = 0.3) +
        ggtitle(titl1)
  y <- score_frame2 %>%
        ggplot(aes(x = score, color = type)) +
        geom_density() +
        egg::theme_article() +
        theme(aspect.ratio = 0.3)+
        ggtitle(titl2)
  gridExtra::grid.arrange(x, y)
}

```

```{r}
raw <- score_type[, c(1,2,4)]
colnames(raw)[3] <- "score"
weighted <- score_type[, c(1,2,3)]
colnames(weighted)[3] <- "score"
```

```{r}
plot_densities(raw, weighted, "Raw Score", "Weighted Score")
```

```{R}
par(mfrow = c(2, 2))

plot(density(score_type$raw_score_all))
plot(density(score_type$weighted_score_all))
```


## Sum Scoring for the Nearest 1, 2, or 3 Amenities

*Note that for nearest 1, the sum is the value itself.*

```{r message=FALSE, warning=FALSE}

# Keep only the nearest 1, 2, or 3 travel times for each dissemination block

nearest_1_ttm <- score_all %>%
                  group_by(fromId, type) %>%
                  summarise(avg_unique_time = min(avg_unique_time), 
                            sd_unique_time = sd_unique_time[which.min(avg_unique_time)],
                            weight = weight[which.min(avg_unique_time)],
                            weighted_score = sum(weighted_score),
                            raw_score = sum(raw_score))

nearest_2_ttm <- score_all %>%
                  group_by(fromId, type) %>%
                  summarise(avg_unique_time = na.omit(sort(avg_unique_time)[1:2]), 
                            sd_unique_time = sd_unique_time[which(na.omit(avg_unique_time == sort(avg_unique_time)[1:2]))], 
                            weight = weight[which(na.omit(avg_unique_time == sort(avg_unique_time)[1:2]))], 
                            weighted_score = sum(weighted_score),
                            raw_score = sum(raw_score))

nearest_3_ttm <- score_all %>%
                  group_by(fromId, type) %>%
                  summarise(avg_unique_time = na.omit(sort(avg_unique_time)[1:3]), 
                            sd_unique_time = sd_unique_time[which(na.omit(avg_unique_time == sort(avg_unique_time)[1:3]))], 
                            weight = weight[which(na.omit(avg_unique_time == sort(avg_unique_time)[1:3]))], 
                            weighted_score = sum(weighted_score),
                            raw_score = sum(raw_score))


# scores by nearest amenities

n1_ttm_score <- normalize_df(nearest_1_ttm, x = 0.001, y = 0.999, log = FALSE)
n2_ttm_score <- normalize_df(nearest_2_ttm, x = 0.001, y = 0.999, log = FALSE)
n3_ttm_score <- normalize_df(nearest_3_ttm, x = 0.001, y = 0.999, log = FALSE)
n1_ttm_score
```

```{r}
raw1 <- n1_ttm_score[, c(1,2,7)]
colnames(raw1)[3] <- "score"
weighted1 <- n1_ttm_score[, c(1,2,6)]
colnames(weighted1)[3] <- "score"

raw2 <- n2_ttm_score[, c(1,2,7)]
colnames(raw2)[3] <- "score"
weighted2 <- n2_ttm_score[, c(1,2,6)]
colnames(weighted2)[3] <- "score"

raw3 <- n3_ttm_score[, c(1,2,7)]
colnames(raw3)[3] <- "score"
weighted3 <- n3_ttm_score[, c(1,2,6)]
colnames(weighted3)[3] <- "score"
```

```{r}
plot_densities(raw1, weighted1, 'Raw Scores 1', 'Weighted Scores 1')
plot_densities(raw2, weighted2, 'Raw Scores 2', 'Weighted Scores 2')
plot_densities(raw3, weighted3, 'Raw Scores 3', 'Weighted Scores 3')
```

